development:
  adapter: postgresql
  database: chapter_app_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: chapter_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: 'chapter-app-production'
  pool: 5
  timeout: 5000
